# Generated by Django 5.2.6 on 2025-10-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='default_lang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fango.language'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
