# Generated by Django 5.2.6 on 2025-10-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fango', '0002_appuser_country_appuser_default_lang_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
