from fango.models import Language

# NOTE: This clears ALL existing data in Languages table
Language.objects.all().delete()

languages = [
    Language(code="en", lang="English"),
    Language(code="ko", lang="Korean"),
    Language(code="ja", lang="Japanese"),
    Language(code="zh", lang="Chinese"),
    Language(code="fr", lang="French"),
    Language(code="es", lang="Spanish"),
    Language(code="de", lang="German"),
    Language(code="it", lang="Italian"),
    Language(code="pt", lang="Portuguese"),
    Language(code="ru", lang="Russian"),
    Language(code="ar", lang="Arabic"),
    Language(code="hi", lang="Hindi"),
    Language(code="th", lang="Thai"),
    Language(code="vi", lang="Vietnamese"),
    Language(code="tl", lang="Tagalog"),
    Language(code="id", lang="Indonesian"),
    Language(code="tr", lang="Turkish"),
    Language(code="nl", lang="Dutch"),
    Language(code="pl", lang="Polish"),
    Language(code="sv", lang="Swedish"),
    Language(code="el", lang="Greek"),
    Language(code="he", lang="Hebrew"),
    Language(code="ms", lang="Malay"),
    Language(code="bn", lang="Bengali"),
    Language(code="ur", lang="Urdu"),
    Language(code="ta", lang="Tamil"),
    Language(code="te", lang="Telugu"),
    Language(code="mr", lang="Marathi"),
    Language(code="pa", lang="Punjabi"),
    Language(code="gu", lang="Gujarati"),
    Language(code="kn", lang="Kannada"),
    Language(code="ml", lang="Malayalam"),
    Language(code="si", lang="Sinhala"),
    Language(code="ne", lang="Nepali"),
    Language(code="my", lang="Burmese"),
    Language(code="km", lang="Khmer"),
    Language(code="lo", lang="Lao"),
    Language(code="mn", lang="Mongolian"),
    Language(code="fa", lang="Persian"),
    Language(code="ps", lang="Pashto"),
    Language(code="ku", lang="Kurdish"),
    Language(code="uk", lang="Ukrainian"),
    Language(code="cs", lang="Czech"),
    Language(code="sk", lang="Slovak"),
    Language(code="hu", lang="Hungarian"),
    Language(code="ro", lang="Romanian"),
    Language(code="bg", lang="Bulgarian"),
    Language(code="sr", lang="Serbian"),
    Language(code="hr", lang="Croatian"),
    Language(code="bs", lang="Bosnian"),
    Language(code="fi", lang="Finnish"),
    Language(code="da", lang="Danish"),
    Language(code="no", lang="Norwegian"),
    Language(code="is", lang="Icelandic"),
    Language(code="sw", lang="Swahili"),
    Language(code="zu", lang="Zulu"),
    Language(code="xh", lang="Xhosa"),
    Language(code="af", lang="Afrikaans"),
    Language(code="ha", lang="Hausa"),
    Language(code="am", lang="Amharic"),
    Language(code="so", lang="Somali"),
    Language(code="yo", lang="Yoruba"),
    Language(code="ig", lang="Igbo"),
]

Language.objects.bulk_create(languages)